version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb_data:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis_data:/data

volumes:
  mongodb_data:
  redis_data:
